# IoT Cyber Range - MQTT Access Control

# Badge Controller
user badge1
topic write facility/badge1/#

# Motion Sensor
user motion1
topic write facility/motion1/#

# Lock Actuator
user lock1
topic write facility/lock1/#

# Backend
user backend
topic read facility/#