# MQTT listener
listener 1883
# Mosquitto listens for MQTT connections on port 1883.

# Plain MQTT for development
protocol mqtt
# tells Mosquitto we're using MQTT.

# Access control
acl_file /mosquitto/config/acl.conf
# tells Mosquitto where our permissions file will be.

# User authentication
password_file /mosquitto/config/passwordfile

# Disable anonymous access
allow_anonymous false